// Data pro detailové stránky (projekty + články) — plní shared renderer v detail.js

export const PROJECTS = {
  'stellar-webovy-dashboard': {
    title: 'Stellar – Webový dashboard',
    lead: 'Stellar — datový dashboard, který mění složitou analytiku v přehledné podklady pro rozhodování.',
    client: 'TechFlow Analytics', year: '2024', duration: '3 měsíce', role: 'UI/UX design',
    overview: 'Stellar je komplexní analytický dashboard pro týmy, které potřebují sledovat klíčové metriky, měřit výkon a rychle se rozhodovat. Výzvou bylo podat rozsáhlé datové sady v intuitivním a vizuálně čistém rozhraní, které snižuje kognitivní zátěž a zároveň maximalizuje vhled do dat.',
    challengeTitle: 'Příliš informací a matoucí struktura',
    challenge: 'Uživatelé se v dosavadních analytických nástrojích ztráceli — příliš informací najednou vedlo k rozhodovací paralýze. Rozhraní postrádalo vizuální hierarchii, klíčové metriky se hledaly obtížně a možnosti přizpůsobení byly minimální.',
    solution: 'Navrhli jsme modulární systém dashboardu s chytrou prioritizací dat. Jasná hierarchie skrze typografii, barvy a odsazení přirozeně vede oko. Přizpůsobitelné widgety umožňují sestavit si ideální pracovní plochu a rozumné výchozí nastavení nezahltí nováčky.',
    hero: 'work-stellar.webp',
    next: { slug: 'lumiere-mobilni-aplikace', title: 'Lumiere – Mobilní aplikace UI/UX', img: 'work-lumiere.webp' },
  },
  'lumiere-mobilni-aplikace': {
    title: 'Lumiere – Mobilní aplikace UI/UX',
    lead: 'Lumiere — mobilní zážitek, který dělá každodenní rutiny jednoduché a příjemné.',
    client: 'Lumiere Health', year: '2024', duration: '4 měsíce', role: 'Produktový design',
    overview: 'Lumiere je mobilní aplikace zaměřená na osobní pohodu a návyky. Cílem bylo navrhnout rozhraní, které motivuje k pravidelnému používání, aniž by působilo nátlakově — jemná gamifikace, čistá typografie a plynulé mikrointerakce.',
    challengeTitle: 'Přeplněné obrazovky a nízká retence',
    challenge: 'Původní aplikace trpěla přehlceným rozhraním a uživatelé ji po pár dnech opouštěli. Klíčové akce byly schované hluboko v navigaci a vizuální styl nepůsobil důvěryhodně.',
    solution: 'Zjednodušili jsme informační architekturu na tři hlavní záložky, klíčové akce jsme dostali na dosah palce a navrhli jsme konzistentní vizuální jazyk s jemnými animacemi, které odměňují pokrok.',
    hero: 'work-lumiere.webp',
    next: { slug: 'echo-branding-identita', title: 'Echo – Branding & identita', img: 'work-echo.webp' },
  },
  'echo-branding-identita': {
    title: 'Echo – Branding & identita',
    lead: 'Echo — soudržná identita značky, která odráží smysl, osobnost a konzistenci.',
    client: 'Echo Studio', year: '2023', duration: '2 měsíce', role: 'Branding & identita',
    overview: 'Echo je kreativní studio, které potřebovalo identitu odpovídající jeho růstu. Vytvořili jsme kompletní vizuální systém — od loga přes typografii a barevnost po pravidla použití napříč digitálními i tištěnými médii.',
    challengeTitle: 'Roztříštěný vizuál bez jasného příběhu',
    challenge: 'Značka používala nekonzistentní vizuální prvky napříč kanály — jiné barvy na webu, jiné v prezentacích. Chyběl jednotný příběh i pravidla, jak s identitou pracovat.',
    solution: 'Postavili jsme identitu na jednoduchém, zapamatovatelném symbolu a definovali škálovatelný systém: paletu, typografické páry, grid a knihovnu šablon, díky které tým udrží konzistenci bez designéra.',
    hero: 'work-echo.webp',
    next: { slug: 'nebrio-eshop-platforma', title: 'Nebrio – E-commerce platforma', img: 'work-nebrio.webp' },
  },
  'nebrio-eshop-platforma': {
    title: 'Nebrio – E-commerce platforma',
    lead: 'Nebrio — nákupní zážitek, který prodává: rychlý, přehledný a bez tření.',
    client: 'Nebrio Commerce', year: '2023', duration: '5 měsíců', role: 'UI/UX design & vývoj',
    overview: 'Nebrio je e-commerce platforma pro střední a větší obchody. Naším úkolem byl redesign nákupního procesu od katalogu po checkout s důrazem na konverze a výkon na mobilu.',
    challengeTitle: 'Dlouhý checkout a vysoká míra opuštění košíku',
    challenge: 'Pětikrokový checkout, nepřehledné varianty produktů a pomalé načítání vedly k nadprůměrné míře opuštění košíku, zejména na mobilních zařízeních.',
    solution: 'Zredukovali jsme checkout na dva kroky, přepracovali produktové karty s jasnou volbou variant a optimalizovali výkon. Výsledkem je plynulý nákup, který nebrání impulzu.',
    hero: 'work-nebrio.webp',
    next: { slug: 'vortex-sprava-socialnich-siti', title: 'Vortex – Správa sociálních sítí', img: 'work-vortex.webp' },
  },
  'vortex-sprava-socialnich-siti': {
    title: 'Vortex – Správa sociálních sítí',
    lead: 'Vortex — jeden nástroj pro všechny sítě: plánování, publikace i analytika.',
    client: 'Vortex Media', year: '2023', duration: '3 měsíce', role: 'Produktový design',
    overview: 'Vortex pomáhá týmům spravovat obsah napříč sociálními sítěmi z jednoho místa. Navrhli jsme rozhraní kalendáře, schvalovacích workflow a reportů tak, aby zvládly agenturní tempo.',
    challengeTitle: 'Chaos v obsahu a zdlouhavé schvalování',
    challenge: 'Týmy plánovaly obsah v tabulkách a schvalovaly e-mailem — verze se ztrácely a termíny hořely. Chyběl jednotný přehled o tom, co, kde a kdy vyjde.',
    solution: 'Srdcem nástroje je vizuální kalendář s drag & drop plánováním, jasné stavy příspěvků a schvalování na jedno kliknutí. Reporty se generují automaticky a šetří hodiny práce měsíčně.',
    hero: 'work-vortex.webp',
    next: { slug: 'alcove-projektovy-nastroj', title: 'Alcove – Nástroj pro řízení projektů', img: 'work-alcove.webp' },
  },
  'alcove-projektovy-nastroj': {
    title: 'Alcove – Nástroj pro řízení projektů',
    lead: 'Alcove — řízení projektů, které nepřekáží práci: přehled bez mikromanagementu.',
    client: 'Alcove Labs', year: '2022', duration: '4 měsíce', role: 'UI/UX design',
    overview: 'Alcove je projektový nástroj pro malé kreativní týmy. Cílem bylo najít rovnováhu mezi jednoduchostí osobního task manageru a silou týmové platformy.',
    challengeTitle: 'Nástroje buď příliš jednoduché, nebo příliš složité',
    challenge: 'Týmy přerostly jednoduché to-do aplikace, ale enterprise nástroje je zahltily funkcemi, které nikdo nepoužíval. Nastavování projektů zabíralo víc času než práce samotná.',
    solution: 'Navrhli jsme systém chytrých výchozích šablon, progresivní odkrývání pokročilých funkcí a přehledy, které odpovídají na otázku „co se děje" na první pohled.',
    hero: 'work-alcove.webp',
    next: { slug: 'crescendo-hudebni-streaming', title: 'Crescendo – Hudební streaming', img: 'work-crescendo.png' },
  },
  'crescendo-hudebni-streaming': {
    title: 'Crescendo – Hudební streaming',
    lead: 'Crescendo — objevování hudby postavené na náladě, ne na algoritmickém stereotypu.',
    client: 'Crescendo Audio', year: '2022', duration: '3 měsíce', role: 'UI/UX design',
    overview: 'Crescendo je streamovací služba zaměřená na nezávislé interprety. Navrhli jsme zážitek objevování hudby podle nálady a kontextu, s důrazem na vizuální identitu umělců.',
    challengeTitle: 'Nekonečné seznamy bez emocí',
    challenge: 'Objevování hudby se smrsklo na scrollování nekonečnými seznamy. Umělci splývali, playlist vypadal jako tabulka a poslech ztrácel atmosféru.',
    solution: 'Rozhraní jsme postavili na velkých vizuálech, náladových kolekcích a plynulých přechodech mezi náhledy. Umělci dostali výrazné profily, které podtrhují jejich identitu.',
    hero: 'work-crescendo.png',
    next: { slug: 'nexus-cloudove-uloziste', title: 'Nexus – Cloudové úložiště', img: 'work-nexus.jpg' },
  },
  'nexus-cloudove-uloziste': {
    title: 'Nexus – Cloudové úložiště',
    lead: 'Nexus — soubory v cloudu srozumitelně: sdílení a spolupráce bez zbytečných kroků.',
    client: 'Nexus Cloud', year: '2021', duration: '4 měsíce', role: 'Produktový design',
    overview: 'Nexus je cloudové úložiště pro firmy. Přepracovali jsme správu souborů, sdílení a oprávnění tak, aby byly pochopitelné i pro netechnické uživatele.',
    challengeTitle: 'Oprávnění, kterým nikdo nerozuměl',
    challenge: 'Systém sdílení byl tak složitý, že uživatelé raději posílali soubory e-mailem. Nejasné stavy synchronizace podkopávaly důvěru v platformu.',
    solution: 'Zjednodušili jsme model oprávnění na tři srozumitelné role, přidali viditelné stavy synchronizace a náhledy souborů přímo v prohlížeči. Sdílení je teď otázka dvou kliknutí.',
    hero: 'work-nexus.jpg',
    next: { slug: 'quantum-virtualni-realita', title: 'Quantum – Virtuální realita', img: 'work-quantum.webp' },
  },
  'quantum-virtualni-realita': {
    title: 'Quantum – Virtuální realita',
    lead: 'Quantum — VR zážitek, který přenáší vzdělávání do prostoru a pohybu.',
    client: 'Quantum XR', year: '2021', duration: '6 měsíců', role: 'UX design & 3D',
    overview: 'Quantum je vzdělávací VR platforma. Navrhovali jsme prostorová rozhraní, navigaci gesty a onboarding, který zvládnou i uživatelé, kteří mají headset poprvé na hlavě.',
    challengeTitle: 'Rozhraní z plochých obrazovek ve 3D prostoru nefungují',
    challenge: 'První prototypy přenášely 2D vzory do VR — plovoucí okna a drobná tlačítka způsobovaly únavu očí a frustraci. Uživatelé se v prostoru ztráceli.',
    solution: 'Navrhli jsme nativně prostorové rozhraní: ovládání ukotvené k rukám, výrazné cíle interakcí a navigaci vedenou světlem a zvukem. Onboarding učí gesta hrou, ne návodem.',
    hero: 'work-quantum.webp',
    next: { slug: 'stellar-webovy-dashboard', title: 'Stellar – Webový dashboard', img: 'work-stellar.webp' },
  },
}

export const POSTS = {
  'navrhovani-se-zamerem': {
    title: 'Design se záměrem: jak z nápadů vznikají smysluplné digitální zážitky',
    perex: 'Dobrý design není o trendech ani vizuálním šumu. Je o záměru, jasnosti a pochopení problému dřív, než začneme tvarovat řešení.',
    category: 'Vývoj', minutes: 12, date: '7. 1. 2026', cover: 'blog-1.webp',
    body: [
      ['Nejdřív pochopit problém', 'Než začne jakákoli designová práce, je potřeba pochopit problém — poznat publikum, cíle byznysu a skutečné potřeby uživatelů. Bez tohoto základu jsou designová rozhodnutí jen domněnky. Promyšlený výzkum a pozorování mění mlhavé nápady v zaostřená řešení.'],
      ['Struktura vytváří jasnost', 'Struktura je páteří efektivního digitálního designu. Jasná hierarchie, odsazení a layout vedou uživatele obsahem přirozeně a bez zmatku. Když jsou informace uspořádané se záměrem, rozhraní působí samozřejmě a uživatel se může soustředit na zážitek, ne na ovládání.'],
      ['Rovnováha kreativity a funkce', 'Kreativita dává designu emoci, funkce mu dává smysl. Když jedno převáží, zážitek trpí. Úspěšné digitální produkty vyvažují výrazný vizuál s použitelností — každé kreativní rozhodnutí musí podporovat interakci, přístupnost a srozumitelnost.'],
      ['Konzistence buduje důvěru', 'Konzistentní typografie, barvy, odsazení a interakce vytvářejí povědomost. Když uživatel rozpozná vzory napříč obrazovkami, pohybuje se produktem s jistotou. Předvídatelnost buduje důvěru a posiluje identitu značky.'],
      ['Ladění je součást procesu', 'Design není jednorázový výstup, ale vyvíjející se proces. Zpětná vazba, testování a iterace odhalují problémy a zlepšují použitelnost. I drobné úpravy odsazení nebo kontrastu často udělají zásadní rozdíl.'],
    ],
  },
  'jasnost-misto-slozitosti': {
    title: 'Design se záměrem: jasnost místo složitosti',
    perex: 'Navigace má uživatele vést, ne testovat. Jak navrhnout systém, ve kterém se nikdo neztratí.',
    category: 'Sociální sítě', minutes: 12, date: '7. 1. 2026', cover: 'blog-2.webp',
    body: [
      ['Méně cest, jasnější směr', 'Každá další položka v menu je další rozhodnutí, které po uživateli chceme. Zúžení navigace na klíčové cesty snižuje kognitivní zátěž a zrychluje orientaci.'],
      ['Pojmenování bez hádanek', 'Kreativní názvy sekcí vypadají dobře v prezentaci, ale uživatel potřebuje předvídatelnost. Srozumitelný jazyk vyhrává nad chytrým — vždy.'],
      ['Kontext místo mapy', 'Dobrá navigace odpovídá na tři otázky: kde jsem, co tu najdu a kam můžu dál. Drobečky, aktivní stavy a jasné titulky drží uživatele v obraze bez přemýšlení.'],
      ['Testujte na skutečných úkolech', 'Strukturu ověřujte úlohami typu „najdi X" — ne dotazem, zda se web líbí. Skutečné chování odhalí slabá místa rychleji než jakýkoli dotazník.'],
    ],
  },
  'proc-na-strukture-zalezi': {
    title: 'Proč na struktuře v digitálním designu záleží',
    perex: 'Vizuální hierarchie není dekorace — je to mechanika, kterou uživatel čte obsah. Struktura rozhoduje, zda sdělení dorazí.',
    category: 'UI/UX Design', minutes: 12, date: '7. 1. 2026', cover: 'blog-3.webp',
    body: [
      ['Oko čte vzory, ne stránky', 'Uživatelé stránky nečtou — skenují je. Jasné bloky, konzistentní odsazení a promyšlené kontrasty dávají skenování rytmus a vedou pozornost tam, kam potřebujete.'],
      ['Grid jako neviditelný pomocník', 'Mřížka není omezení kreativity, ale nástroj konzistence. Zarovnané prvky snižují vizuální šum a dávají layoutu klid, i když obsahu přibývá.'],
      ['Bílé místo pracuje', 'Prázdný prostor není promarněný prostor. Odsazení odděluje myšlenky, zvýrazňuje důležité a dává obsahu nadechnout. Přeplněná stránka křičí — a nikdo ji neposlouchá.'],
      ['Struktura škáluje', 'Promyšlená struktura unese růst: nové sekce, další jazyky, jiná zařízení. Ad hoc layout se rozpadne s první změnou zadání.'],
    ],
  },
  'kreativita-a-pouzitelnost': {
    title: 'Rovnováha mezi kreativitou a použitelností',
    perex: 'Výrazný design přitáhne pozornost, použitelný design ji udrží. Jak najít bod, kde se obojí potkává.',
    category: 'UI/UX Design', minutes: 12, date: '7. 1. 2026', cover: 'blog-4.webp',
    body: [
      ['Kreativita s kotvou', 'Experiment je zdravý, pokud drží základní vzory chování. Uživatel odpustí nečekaný vizuál, ale ne nefunkční tlačítko.'],
      ['Animace se záměrem', 'Pohyb má vysvětlovat — odkud prvek přišel, co se změnilo, kam zmizel. Animace pro efekt bez významu jen zdržuje a unavuje.'],
      ['Adaptabilní layouty', 'Rozvržení, které se přizpůsobí zařízení i obsahu, zvyšuje použitelnost napříč kontexty. Responzivita není checkbox, ale způsob myšlení o obsahu.'],
      ['Měřit, ne hádat', 'Krása je subjektivní, použitelnost se dá měřit. Míra dokončení úloh, čas na úkol a návratnost uživatelů ukážou, zda kreativní rozhodnutí pomáhají, nebo škodí.'],
    ],
  },
  'socialni-site-pro-rust-znacky': {
    title: 'Sociální sítě jako motor růstu značky',
    perex: 'Sociální sítě nejsou nástěnka na loga. Jsou to místa, kde značka mluví, poslouchá a buduje vztah.',
    category: 'Sociální sítě', minutes: 12, date: '7. 1. 2026', cover: 'blog-5.webp',
    body: [
      ['Konzistence napříč kanály', 'Každá síť má svůj jazyk, ale značka musí zůstat rozpoznatelná. Jednotný vizuální systém — barvy, typografie, tón — drží identitu pohromadě i v odlišných formátech.'],
      ['Obsah s hodnotou', 'Algoritmy se mění, ale princip zůstává: sdílejte to, co publiku skutečně pomáhá nebo ho baví. Prodejní příspěvky bez kontextu vztah spíš podkopávají.'],
      ['Rytmus místo náporu', 'Pravidelný, udržitelný publikační rytmus poráží nárazové kampaně. Plánovací kalendář a šablony šetří energii na to podstatné — nápady.'],
      ['Data jako kompas', 'Sledujte, co rezonuje, a přizpůsobujte se. Analytika není reporting pro reporting — je to zpětná vazba od publika v reálném čase.'],
    ],
  },
  'konzistence-buduje-duveru': {
    title: 'Konzistence jako základ digitální důvěry',
    perex: 'Důvěra se nebuduje velkými gesty, ale tisíci drobných potvrzení, že se věci chovají, jak uživatel čeká.',
    category: 'Branding', minutes: 12, date: '7. 1. 2026', cover: 'blog-6.webp',
    body: [
      ['Předvídatelnost uklidňuje', 'Když tlačítka vypadají a fungují stejně napříč produktem, uživatel přestane přemýšlet o ovládání a soustředí se na obsah. To je ta nejlepší vizitka rozhraní.'],
      ['Design tokeny v praxi', 'Sdílené proměnné pro barvy, odsazení a typografii udrží konzistenci i ve velkém týmu. Změna na jednom místě se propíše všude — bez honění odchylek.'],
      ['Hlas značky', 'Konzistence není jen vizuální. Tón komunikace — od chybových hlášek po e-maily — tvoří osobnost, kterou si uživatel zapamatuje.'],
      ['Výjimky se záměrem', 'Porušit vzor je občas správné — ale vědomě a s důvodem. Nahodilé odchylky působí jako chyby a důvěru drolí.'],
    ],
  },
  'design-systemy': {
    title: 'Design systémy: řád uvnitř kreativní svobody',
    perex: 'Dobrý design systém není klec. Je to společný jazyk, který uvolňuje ruce pro důležitější rozhodnutí.',
    category: 'UI/UX Design', minutes: 12, date: '7. 1. 2026', cover: 'blog-7.webp',
    body: [
      ['Systém jako produkt', 'Design systém potřebuje vlastníka, roadmapu a zpětnou vazbu jako každý jiný produkt. Bez péče zastará a týmy ho obejdou.'],
      ['Komponenty s pravidly', 'Knihovna komponent bez dokumentace je jen hromada dílků. Pravidla použití — kdy, kde a proč — dělají ze stavebnice systém.'],
      ['Svoboda v mantinelech', 'Paradox design systémů: čím pevnější základy, tím odvážnější mohou být kreativní vrstvy nad nimi. Řešené základy uvolňují kapacitu pro inovaci.'],
      ['Začněte malí', 'Nezačínejte stostránkovou dokumentací. Barvy, typografie, tlačítka a formuláře pokryjí většinu potřeb — zbytek přidávejte podle skutečné poptávky.'],
    ],
  },
}
